config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, presence: true
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list, message: 'Already added?' }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :overview, presence: true
  validates :title, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to lists_path, class: "navbar-brand" do %>
    <i class="fas fa-film"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

      </li>
      <li class="nav-item">
      </li>
      <li class="nav-item dropdown">
      <i class="fas fa-bars avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Create a list", new_list_path, class: "dropdown-item" %>
<!--           <%= link_to "Another action", "#", class: "dropdown-item" %> -->
        </div>
      </li>
    </ul>
  </div>

  </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="slides banner-container">
     <div class="banner-text">
        <h1>My best watch List</h1>
        <p>
          <span id="banner-typed-text" ></span>
        </p>
      </div>
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="d-block w-100" src="https://picsum.photos/id/318/1200/800"alt="Eifel Tower">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://picsum.photos/id/91/1200/800" alt="camera">
        </div>
        <div class="carousel-item">
          <img class="d-block w-100" src="https://picsum.photos/id/43/1200/800" alt="Bridge">
        </div>
      </div>
    </div>
  </div>


<div>
  <h2 class="text-center my-5">All lists</h2>
 <!--  <%= link_to 'Create a new list', lists_path, class:"hidden-form" %> -->
  <div class="d-flex justify-content-end rounded mb-3"><%= link_to "Create a list", new_list_path, class:"btn btn-success" %></div>
    <div class="cards">
      <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
          <h3> <%= link_to list.name, list_path(list.id) %></h3>
        </div>
      <% end %>
    </div>
  </div>

app/views/lists/new.html.erb
<div class="pages container">
  <h1>Create a list</h1>
  <%= simple_form_for(@list) do |f|%>
    <%= f.input :name %>
    <%= f.input :photo, as: :file, class:"btn btn-secondary"%>
    <%= f.submit class:"btn btn-success"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="pages">

  <div class="banner-films relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuL97GQjwnCpecWlImPTAezL6zmJt4gupb3A&usqp=CAU);">
    <div class= "absolute"><%= @list.bookmarks.count %> movies</div>
    <div class="container">
      <h1 class="text-center"><%= @list.name %></h1>
    </div>
  </div>

  <div class="container">
    <div class="d-flex justify-content-end my-3 rounded">
    <a href="#add-book" class="btn btn-success">Add a movie</a>
    </div>
    <div class="cards-films">
      <% if @list.bookmarks.count == 0 %>
      <%= '<h2>There is no films yet</h2>'.html_safe %>
      <% else %>
        <% @list.bookmarks.each do |bookmark| %>
        <div class="card-film border-secondary" >
          <img src='<%= bookmark.movie.poster_url %>' alt="Card image cap">
          <div >
            <div>
              <h4 class="my-2 px-2" ><strong><%= bookmark.movie.title %></strong></h4>
              <p class="px-2">Rating: <%= bookmark.movie.rating %><i class="fas fa-star" style="color:#ffe900"></i></p>
            </div>
            <p class="px-2"><%= bookmark.movie.overview %></p>
            <div class="d-flex justify-content-between">
              <p class="px-2"><i class="fas fa-quote-left"></i> <%= bookmark.comment %></p>
            <%= link_to"Delete",  bookmark_path(bookmark), method: :delete, data: { confirm: "Sure?"}, class:"btn btn-danger rounded m-2"%></div>
          </div>
        </div>
        <% end%>
      <% end %>
    </div>
  </div>
    <div id="add-book" class="container my-5">
      <div >
        <%= simple_form_for [@list, @bookmark] do |f|%>
        <%= f.input :comment %>
        <%= f.association :movie %>
        <%= f.submit class:"btn btn-success"%>
        <% end %>
      </div>
  </div>
</div>